// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: test

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ArcLed = NULL;
lv_obj_t * ui_BtnLed = NULL;
// event funtions
/*void ui_event_ArcLed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_ArcLed(e);
    }
}

void ui_event_BtnLed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_BtnLed(e);
    }
}*/

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ArcLed = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcLed, 150);
    lv_obj_set_height(ui_ArcLed, 150);
    lv_obj_set_x(ui_ArcLed, 3);
    lv_obj_set_y(ui_ArcLed, -36);
    lv_obj_set_align(ui_ArcLed, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcLed, 50);

    ui_BtnLed = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_BtnLed, 100);
    lv_obj_set_height(ui_BtnLed, 50);
    lv_obj_set_x(ui_BtnLed, 6);
    lv_obj_set_y(ui_BtnLed, 75);
    lv_obj_set_align(ui_BtnLed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnLed, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnLed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ArcLed, ui_event_ArcLed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnLed, ui_event_BtnLed, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_ArcLed = NULL;
    ui_BtnLed = NULL;

}
